spring.application.name=${SPRING_APPLICATION_NAME:service-registry}
server.port=${SERVER_PORT:8761}

# Graceful shutdown (Factor IX Disposability)
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Eureka Server Config
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:service-registry}

# Eureka server does not register itself
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

