spring.application.name=service-registry
server.port=8761

# Use Docker service name, not localhost
eureka.instance.hostname=service-registry

# Eureka server does not register itself
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
