spring.application.name=api-gateway
server.port=8765

# Eureka client config
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

# Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
