spring.application.name=${SPRING_APPLICATION_NAME:api-gateway}
server.port=${SERVER_PORT:8765}

# Graceful shutdown (Factor IX Disposability)
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s

# Eureka client config
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}

# Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true



# --- MVC Gateway Routes ---
spring.cloud.gateway.mvc.routes[0].id=test-wheel-mvc
spring.cloud.gateway.mvc.routes[0].uri=lb://SPRING-SECURITY
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/wheel/**
spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.mvc.routes[0].filters[1]=CircuitBreaker=wheelServiceCB,forward:/fallback/wheel

spring.cloud.gateway.mvc.routes[1].id=test-service-mvc
spring.cloud.gateway.mvc.routes[1].uri=lb://TEST-SERVICE
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/test/**
spring.cloud.gateway.mvc.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.mvc.routes[1].filters[1]=CircuitBreaker=testServiceCB,forward:/fallback/test

spring.cloud.gateway.mvc.routes[2].id=default-home-mvc
spring.cloud.gateway.mvc.routes[2].uri=forward:/home
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/



spring.mvc.pathmatch.matching-strategy=ant_path_matcher
